name: Javascript Linter
on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Linter
        run: npm install eslint

      - name: Check Codestyle
        run: npx eslint . --ext .js
