name: Javascript Linter
on:
  push:
    branches:
      - main

jobs:
  style:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install Linter
        run: npm install eslint

      - name: Check Codestyle
        run: npx eslint . --ext .js
