name: Javascript Linter

on: [workflow_dispatch]

jobs:
  style:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install Linter
        run: npm install eslint

      - name: Check Codestyle
        run: npx eslint . --ext .js
