name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download and install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.33.0/trivy_0.33.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.33.0_Linux-64bit.deb
      - name: Generate SBOM
        run: trivy fs --format cyclonedx --security-checks vuln --output sbom.json .
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json
          
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Run Docker Compose
        run: docker-compose -f docker-compose.yaml up -d
      
      - name: Scan for vulnerabilities
        run: trivy fs --exit-code 0 --severity CRITICAL,HIGH .
